DROP TABLE IF EXISTS operator CASCADE;
DROP TABLE IF EXISTS reception_center CASCADE;
DROP TABLE IF EXISTS reception_data CASCADE;
DROP TABLE IF EXISTS reception_session CASCADE;
DROP TABLE IF EXISTS satellite CASCADE;
DROP TYPE IF EXISTS datafiletype CASCADE;
DROP TYPE IF EXISTS orbittype CASCADE;
DROP TYPE IF EXISTS workstatustype CASCADE;